"""jokes_revision

Revision ID: d1802b2880bd
Revises: 9163b5e32020
Create Date: 2022-09-15 20:47:08.880344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1802b2880bd'
down_revision = '9163b5e32020'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "joke",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joke_description"), "joke", ["description"], unique=False)
    op.create_index(op.f("ix_joke_id"), "joke", ["id"], unique=False)
    op.create_index(op.f("ix_joke_title"), "joke", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_title"), table_name="joke")
    op.drop_index(op.f("ix_item_id"), table_name="joke")
    op.drop_index(op.f("ix_item_description"), table_name="joke")
    op.drop_table("joke")
